### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by book000** [book000/book000#15]
- 作業時間計測アプリ、予定記録アプリ
- PWA
- 15分刻み
- スタート/ストップボタンを押すと、次の15分区切りの時間を記録する
- 記録には箇条書きの作業メモをつけられる
- それぞれの時間を出力
- 最終的にはMarkdownで出力、ダウンロード
- local storageで保持

**Comment by Omuretsu** [comment]
一応iPadOSでポモドーロタイマーのアプリがあります。
https://apps.apple.com/jp/app/flat-tomato-pomodoro-ポモドーロ/id719462746
